#!/bin/bash
set -x
set +H

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RETAIN=1000
NOW=$(date +'%Y%m%d-%H%M%S')

SOAK_TIME=60
IFTOP_HOST="$THIS_DIR/iftop -s $SOAK_TIME -L 10"
IFTOP_PORT="$THIS_DIR/iftop -s $SOAK_TIME -L 50 -P"
FILE_PREFIX=top
FILE_POSTFIX=txt
OUTPUT_DIR=/data/ifbwu

mkdir -p $OUTPUT_DIR

$IFTOP_HOST > $OUTPUT_DIR/$NOW.top10host.$FILE_POSTFIX
$IFTOP_PORT > $OUTPUT_DIR/$NOW.top50port.$FILE_POSTFIX

if (( $(ls -1 $OUTPUT_DIR | wc -l) > $RETAIN )); then
	for BACKUP in $(ls -1 $OUTPUT_DIR | head -n -$RETAIN); do
		\rm -f $OUTPUT_DIR/$BACKUP
	done
fi
