#!/bin/bash
set -x
set +H

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RETAIN=1000
NOW=$(date +'%Y%m%d-%H%M%S')

SOAK_TIME=60
IFTOP="$THIS_DIR/iftop -s $SOAK_TIME -L 10"
IFTOP_SHOWPORT="$THIS_DIR/iftop -P -s $SOAK_TIME -L 50"
FILE_PREFIX=iftop
FILE_POSTFIX=txt
OUTPUT_DIR=history

mkdir -p $THIS_DIR/$OUTPUT_DIR

$IFTOP > $THIS_DIR/$OUTPUT_DIR/$FILE_PREFIX.$NOW.$FILE_POSTFIX
$IFTOP_SHOWPORT > $THIS_DIR/$OUTPUT_DIR/$FILE_PREFIX.$NOW.p.$FILE_POSTFIX

if (( $(ls -1 $THIS_DIR/$OUTPUT_DIR | wc -l) > $RETAIN )); then
	for BACKUP in $(ls -1 $THIS_DIR/$OUTPUT_DIR | head -n -$RETAIN); do
		\rm -f $THIS_DIR/$OUTPUT_DIR/$BACKUP
	done
fi
